- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx package
    ansible.legacy.dnf:
      name: nginx
      status: present
  - name: run nginx
    ansible.legacy.dnf:
       name: nginx
       status: started