- name: install and run nginx
  hosts: web
  tasks:
  - name: install nginx package
    ansible.builtin.package:
     name: nginx
     status: present
  - name: run nginx
    ansible.builtin.package:
      name: nginx
      status: started