- name: variables
  host: localhost
  var:
    Course: "Devops"
    Trainer: "Siva"
    Duration: "110HRS"
   tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}} and Duration is {{Duration}}"