# Task level variables
- name: Task level variable
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Siva"
    Duration: "110HRS"
  tasks:
  - name: check variables
    vars: 
      Course: "DevOps with AWS"
    ansible.builtin.debug:
      msg: "Hi, I am leaning {{Course}}, Trainer is {{Trainer}} and Duration is {{Duration}}"