- name: install and run nginx in multiple servers
  hosts: roboshop:children
  become: yes
  tasks:
  - name: install nginx package
    ansible.legacy.dnf:
      name: nginx
      state: present
      update_cache: yes
      name: Start nginx service
      systemd:
        name: nginx
        state: started  # Correct state to start the service
        enabled: yes  # Ensure nginx starts on boot

  - name: Restart nginx service 
    systemd:
    name: nginx
    state: restarted

  - name: Open firewall for HTTP and HTTPS
    ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
    loop:
    - http
    - https
    