- name: Install nginx in multiple servrs
  host: localhost
  vars: servers
  become: yes
  tasks:
  - name: install nginx package
    ansible.builtin.pacakge:
     name: nginx
     state: present
  - name: run nginx 
    ansible.builtin.package:
      name: nginx
      state: started

  - name: Open firewall for HTTP and HTTPS
    ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
    loop:
    - http
    - https
    