- name: install and run nginx in multiple servers
  hosts: roboshop:children
  become: yes
  tasks:
  - name: install nginx package
    ansible.legacy.dnf:
      name: nginx
      state: present
      update_cache: yes
  - name: Start nginx service
    ansible.builtin.service:
        name: nginx
        state: started  # Correct state to start the service
        enabled: yes  # Ensure nginx starts on boot

  - name: Restart nginx service 
    ansible.builtin.service:
      name: nginx
      state: restarted

  
    