- name: install and run nginx in multiple servers
  hosts: localhost
  become: yes
  tasks:
  - name: install nginx package
    ansible.builtin.package:
      name: nginx
      state: present
      update_cache: yes
  - name: run nginx
    ansible.legacy.dnf:
       name: nginx
       state: latest
       enabled: yes

  - name: Open firewall for HTTP and HTTPS
    ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
    loop:
    - http
    - https
    