- name: install nginx in multiple servrs
  host: servers 
  become: yes
  tasks:
  - name: install nginx package
    ansible.builtin.pacakge:
     name: nginx
     state: present
  - name: run nginx 
    ansible.builtin.package:
      name: nginx
      state: started