- name: install and run nginx in multiple servers
  hosts: roboshop:children
  become: yes
  tasks:
  - name: install nginx package
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.package:
       name: nginx
       state: latest
       ignore_errors: true # ansible will not exit even we got error

  - name: Open firewall for HTTP and HTTPS
    ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
    loop:
    - http
    - https
    